item	{
	id:	1
	name:	'Grey Leaf Spot'
}
item	{
	id:	2
	name:	'Bacterial Blight'
}
item	{
	id:	3
	name:	'Powdery mildew'
}
item	{
	id:	4
	name:	'Rust'
}
item	{
	id:	5
	name:	'Downy mildew'
}
item	{
	id:	6
	name:	'Leaf Hopper'
}
item	{
	id:	7
	name:	'Turcicum Leaf blight'
}
item	{
	id:	8
	name:	'Fall Army worm'
}
item	{
	id:	9
	name:	'Brown Plant Hopper'
}
item	{
	id:	10
	name:	'Leaf folder'
}
item	{
	id:	11
	name:	'Aphids'
}
item	{
	id:	12
	name:	'Mealy bug'
}
item	{
	id:	13
	name:	'Stem borer'
}
